// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdjwumlbnptsbvffutgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkand1bWxibnB0c2J2ZmZ1dGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjU3NTIsImV4cCI6MjA1Nzk0MTc1Mn0.f4MWYWnqQ6yzuylu2tNqa4Q2vq2glQl32vmFVt8Pmpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);